controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    drive_controller:
      type: velocity_controllers/JointGroupVelocityController

    pivot_controller:
      type: position_controllers/JointGroupPositionController

drive_controller:
  ros__parameters:
    joints:
      - wheel1
      - wheel2
      - wheel3
      - wheel4
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

pivot_controller:
  ros__parameters:
    joints:
      - pivot_right
      - pivot_left
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity